import {
  Activity,
  BellRing,
  Binary,
  Bot,
  Boxes,
  BrickWall,
  Cable,
  Cloud,
  Cog,
  Database,
  DatabaseBackup,
  Globe,
  HardDrive,
  KeyRound,
  LifeBuoy,
  LockKeyhole,
  MonitorSmartphone,
  Network,
  Radar,
  Search,
  Server,
  Webhook,
  Workflow,
  type LucideIcon,
} from "lucide-react";

// Pictogrammes (lucide) pour les badges SANS logo de marque (concepts, protocoles,
// marques absentes de simple-icons) — partagés entre Skills et Projets.
export const GENERIC_ICONS: Record<string, LucideIcon> = {
  // compétences (Skills)
  ESXi: Boxes, // hyperviseur → cubes empilés (les VM), distinct du logo VMware
  systemd: Cog,
  VLAN: Network,
  DNS: Globe,
  "IPv4/IPv6": Binary,
  iptables: BrickWall,
  SSH: KeyRound,
  iSCSI: HardDrive,
  "Responsive design": MonitorSmartphone,
  SEO: Search,
  "API REST": Webhook,
  "CI/CD": Workflow,
  AWS: Cloud,
  "SQL Server": Database,
  // badges projets
  Responsive: MonitorSmartphone,
  Réseau: Network,
  "10 GbE": Cable,
  "self-hosting": Server,
  Beszel: Activity,
  UptimeRobot: Radar,
  Alerting: BellRing,
  restic: DatabaseBackup,
  Chiffrement: LockKeyhole,
  RAID1: HardDrive,
  Automatisation: Bot,
  PRA: LifeBuoy,
};
